### PR TITLE
Store local copy of Campbell's proposal

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by arthurgleckler** [comment]
This is a good idea, but the new authors, Wolfgang and Marc, should review it.  Would you please send the pull request to them, too?  I can't seem to add them myself in the Reviewers box.

**Comment by lassik** [comment]
@Zipheir @mnieper

**Comment by mnieper** [comment]
I think this patch should be applied to the original SRFI 249, not SRFI 255.

The restarter mechanism we will describe in SRFI 255 is a fresh design.

**Comment by arthurgleckler** [comment]
Lassi sent me a pull request to do that in SRFI 249.  I've merged and pushed it.

**Pull request closed without merging**
